[package]
name = "mandelbrot-web"
version = "0.1.0"
authors = ["Jerome Froelich <jeromefroelich@hotmail.com>"]
edition = "2018"

[dependencies]
futures-preview = "=0.3.0-alpha.17"
tokio = "=0.2.0-alpha.1"
rand = "0.7.0"
