[package]
name = "mandelbrot-web"
version = "0.1.0"
authors = ["Jerome Froelich <jeromefroelich@hotmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
tokio = { version = "1.25.0", features = ["full"] }
num = "0.4.0"
image = "0.24.5"
