[package]
name = "mandelbrot-web"
version = "0.1.0"
authors = ["Jerome Froelich <jeromefroelich@hotmail.com>"]
edition = "2018"

[dependencies]
futures-preview = "0.3.0-alpha.16"
romio = "0.3.0-alpha.9"
